import { Artist } from '@/lib/types';

export const artistsData: Artist[] = [
  {
    id: "1",
    name: "The Eighteen Art Collective",
    isAlive: true,
    title: "Black Lives Matter Street Mural",
    medium: "Street Paint / Public Mural",
    date: "August 2020",
    location: "Indianapolis (Indiana Avenue)",
    cause: "Racial Justice",
    bio: "The Eighteen Art Collective is a group of 18 Indianapolis-based Black artists who came together in 2020 to paint the 'Black Lives Matter' mural on Indiana Avenue. They have since formalized as a collective to advocate for equity, civic engagement, and the support of Black creatives in the city.",
    workDescription: "A massive street mural where each of the 18 artists was assigned one letter of the phrase 'Black Lives Matter.' The mural is a vibrant affirmation of Black life and culture, located on a street with deep historical significance to Indianapolis's Black community.",
    searchQuery: "The Eighteen Art Collective Indianapolis",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "2",
    name: "Gary Gee",
    isAlive: true,
    title: "We the People",
    medium: "Acrylic on Plywood Banner",
    date: "2020",
    location: "Indianapolis (Archived by IndyPL)",
    cause: "Civil Rights, Police Brutality",
    bio: "Gary Gee is a multidisciplinary artist from Indianapolis who bridges the gap between street art and fine art. His work often incorporates ceramics, mixed media, and bold graphic styles to explore themes of urban life, hip-hop culture, and social justice.",
    workDescription: "Part of the 'Murals for Racial Justice', this panel depicts a diverse group of protesters demanding justice. The work contrasts the constitutional ideal of 'We the People' with the reality of police brutality and systemic inequality faced by marginalized communities.",
    searchQuery: "Gary Gee artist Indianapolis",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "3",
    name: "Mechi Shakur (Demetrius Green)",
    isAlive: true,
    title: "Blkkk Lives Don't Matter",
    medium: "Acrylic on Plywood Banner",
    date: "2020",
    location: "Indianapolis (Archived by IndyPL)",
    cause: "Racial Justice, Police Brutality",
    bio: "Mechi Shakur (Demetrius Green) is a self-taught visual artist whose work is characterized by raw emotion and intense social commentary. He often uses his art to challenge comfort zones and confront viewers with the harsh realities of racial violence and systemic oppression.",
    workDescription: "A powerful, eight-panel work created on boarded-up windows during the 2020 protests. The provocative title and imagery serve as a direct confrontation of the violence against Black bodies, challenging the viewer to acknowledge the disparity in how lives are valued.",
    searchQuery: "Mechi Shakur artist",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "4",
    name: "Israel Solomon",
    isAlive: true,
    title: "American Duality",
    medium: "Art/Mural on Plywood",
    date: "2020",
    location: "Indianapolis",
    cause: "Social Justice (General)",
    bio: "Israel Solomon is a visual artist and educator known for his geometric, cubist-inspired style and vibrant use of color. His work frequently focuses on community, family, and the Black experience, often creating portraits that elevate everyday people to icons.",
    workDescription: "This piece explores the split experience of American life, highlighting the stark differences in safety, policing, and opportunity faced by Black Americans versus their white counterparts.",
    searchQuery: "Israel Solomon artist Indianapolis",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "5",
    name: "Fred Wilson",
    isAlive: true,
    title: "E Pluribus Unum",
    medium: "Sculptural Intervention (Proposed/Cancelled)",
    date: "2007-2011",
    location: "Indianapolis (Not Installed)",
    cause: "Racial Justice, Historical Reconciliation",
    bio: "Fred Wilson is a world-renowned conceptual artist known for his practice of 'mining the museum,' where he rearranges and recontextualizes objects to reveal hidden histories of racism and exclusion. He represented the U.S. at the Venice Biennale in 2003.",
    workDescription: "This controversial project proposed remixing the Soldiers' and Sailors' Monument by isolating the sole African American figure (a formerly enslaved man) and elevating him on a new pedestal holding a flag of the African diaspora. The project was cancelled due to public controversy.",
    searchQuery: "Fred Wilson artist",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "6",
    name: "Robert Indiana (Robert Clark)",
    isAlive: false,
    born: "1928",
    died: "2018",
    title: "The Confederacy: Mississippi",
    medium: "Oil on Canvas",
    date: "1965",
    location: "Various Collections",
    cause: "Civil Rights",
    bio: "Robert Indiana was a preeminent figure in the Pop Art movement, best known for his iconic 'LOVE' series. Born in Indiana, his work often used bold text and hard-edge painting to critique American politics, identity, and the deceptive nature of the 'American Dream.'",
    workDescription: "Part of his 'Confederacy' series, this work is a blunt critique of Southern racism during the Civil Rights era. It features a map of Mississippi and references the 1964 murders of civil rights workers, condemning the state's violent resistance to justice.",
    searchQuery: "Robert Indiana artist",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "7",
    name: "Samuel Levi Jones",
    isAlive: true,
    title: "Poplar Trees",
    medium: "Deconstructed Books on Canvas",
    date: "2015",
    location: "IU Eskenazi Museum of Art (Bloomington)",
    cause: "Racial Justice",
    bio: "Samuel Levi Jones is an artist who challenges the authority of established history by physically deconstructing institutional materials like encyclopedias and law books. He strips the covers and reassembles them into abstract grids, visually dismantling the systems that have historically excluded marginalized voices.",
    workDescription: "A diptych made from the skins of deconstructed books. The title references the song 'Strange Fruit' and the history of lynching (poplar trees), using the medium itself to critique how history and law have been used to oppress rather than protect.",
    searchQuery: "Samuel Levi Jones artist",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "8",
    name: "Shauta Marsh & Jim Walker",
    isAlive: true,
    title: "Social Alchemy",
    medium: "Social Practice / Community Engagement",
    date: "Ongoing (Since 2005)",
    location: "Indianapolis (Garfield Park)",
    cause: "Social Connection",
    bio: "Shauta Marsh and Jim Walker are the co-founders of Big Car Collaborative, a non-profit arts organization. They specialize in 'creative placemaking,' using art to transform public spaces, build social cohesion, and improve quality of life in Indianapolis neighborhoods.",
    workDescription: "'Social Alchemy' is a multi-year project exploring the concepts of utopia and dystopia, drawing inspiration from New Harmony, Indiana. It uses art, radio, and design to facilitate social connection and reimagine how communities can live better together.",
    searchQuery: "Big Car Collaborative Social Alchemy",
    imageUrl: "/placeholder.svg?height=400&width=600",
    link: "https://bigcar.org"
  },
  {
    id: "9",
    name: "Andre Portee (AbsorbALL)",
    isAlive: true,
    title: "McMillen Park Basketball Court Murals",
    medium: "Court Paint / Public Art",
    date: "2020",
    location: "Fort Wayne (McMillen Park)",
    cause: "Racial Justice, Placemaking",
    bio: "Andre Portee is a Fort Wayne-based creative and the founder of AbsorbALL. He focuses on using art as a tool for community revitalization, specifically targeting public spaces in underserved neighborhoods to instill pride and ownership.",
    workDescription: "A massive, vibrant mural painted directly onto the basketball courts of McMillen Park. The project revitalized a gray, neglected space into a colorful destination, celebrating Black culture and providing a beautiful, dignified space for youth recreation.",
    searchQuery: "Portee AbsorbALL Fort Wayne",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "10",
    name: "Rachel Kavathe",
    isAlive: true,
    title: "McDoel Blooms",
    medium: "Street Mural / Public Art",
    date: "2025",
    location: "Bloomington (Allen & Fairview Streets)",
    cause: "Social Connection, Placemaking",
    bio: "Rachel Kavathe is an artist and landscape architect whose work lies at the intersection of nature, community, and urban design. She creates site-specific installations that highlight the identity of neighborhoods and the natural ecosystems they inhabit.",
    workDescription: "A street mural project designed to calm traffic and beautify the McDoel Gardens neighborhood. The design features native flora and garden imagery, reflecting the neighborhood's history and the shared values of its residents.",
    searchQuery: "Rachel Kavathe artist",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "11",
    name: "Kacy Jackson",
    isAlive: true,
    title: "Faces of the Fort: Southeast Mural",
    medium: "Acrylic on Building / Mural",
    date: "June 2021",
    location: "Fort Wayne (4335 S Anthony Blvd)",
    cause: "Civil Rights, Immigration",
    bio: "Kacy Jackson, founder of 'The Art of Kacy', is a muralist known for his photorealistic portraits and ability to capture the human spirit. His work is dedicated to storytelling and uplifting community heroes through large-scale public art.",
    workDescription: "This mural honors local figures Irene Paxia, who supports refugees, and William E. Warfield, a historic Black real estate investor. It celebrates the contributions of immigrants and Black leaders to the fabric of Fort Wayne.",
    searchQuery: "The Art Of Kacy",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "12",
    name: "Benjamin Duke",
    isAlive: true,
    title: "Faces of the Fort: Northeast Mural",
    medium: "Acrylic on Building / Mural",
    date: "June 2021",
    location: "Fort Wayne (1514 St. Joseph Blvd)",
    cause: "Racial Justice, Inclusive Community",
    bio: "Benjamin Duke is a painter and professor at Michigan State University. His studio work often involves complex, figurative narratives, which translates into his murals as dynamic, multi-layered compositions that tackle history and social justice.",
    workDescription: "The mural depicts Glynn Hines, a long-time advocate for racial justice, and Genevieve Meyer, a crusader against child marriage in Indiana. It highlights the ongoing fight for legislative and social protection of vulnerable groups.",
    searchQuery: "Benjamin Duke artist Michigan State",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "13",
    name: "Mitchell Egly",
    isAlive: true,
    title: "Faces of the Fort: Southwest Mural",
    medium: "Acrylic on Building / Mural",
    date: "June 2021",
    location: "Fort Wayne (1818 Bluffton Road)",
    cause: "Social Justice (General)",
    bio: "Mitchell Egly is a Fort Wayne native and artist who specializes in large-scale public works that engage with local history. He returned to his hometown to contribute to its artistic renaissance, focusing on themes of civic pride and history.",
    workDescription: "A tribute to diverse local leaders who have shaped the community's history. The mural serves as a visual history lesson, ensuring that the contributions of civil rights leaders and community builders are not forgotten.",
    searchQuery: "Mitchell Egly artist Fort Wayne",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "14",
    name: "May Wright Sewall",
    isAlive: false,
    born: "1844",
    died: "1920",
    title: "Founding the Art Association of Indianapolis",
    medium: "Institution Building",
    date: "1883",
    location: "Indianapolis",
    cause: "Women's Suffrage, Education",
    bio: "May Wright Sewall was a legendary suffragist, educator, and peace activist. A close ally of Susan B. Anthony, she believed that access to culture and education was essential for women's liberation, leading her to found the Art Association (now Newfields) and the Propylaeum.",
    workDescription: "While not a visual artwork, her 'work' was the creation of the institutions themselves. She leveraged her influence to create spaces where women could organize, learn, and engage with the arts, laying the cultural foundation of Indianapolis.",
    searchQuery: "May Wright Sewall",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "15",
    name: "Florita Eichel",
    isAlive: false,
    born: "1892",
    died: "1983",
    title: "Suffrage Movement Involvement & Guild Founding",
    medium: "Activism / Curatorial Work",
    date: "Early 1900s",
    location: "Evansville, Indiana",
    cause: "Women's Suffrage",
    bio: "Florita Eichel was a pioneering artist and suffragist in Evansville, Indiana. She joined the suffrage movement at age 20 and later became a key figure in the local arts scene, founding the Evansville Artists Guild to support professional artists in the region.",
    workDescription: "Eichel used her position to bridge political activism and the arts in Southern Indiana. Her legacy is the professionalization of the arts in Evansville and her early grassroots work securing the vote for women in the state.",
    searchQuery: "Florita Eichel artist Evansville",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "16",
    name: "Kassie Woodworth",
    isAlive: true,
    title: "Together",
    medium: "Quilt (Mixed media)",
    date: "2020",
    location: "Indianapolis (Indiana Statehouse)",
    cause: "Women's Suffrage, Racial Justice",
    bio: "Kassie Woodworth is an Indianapolis-based sculptor and fiber artist. Her work often utilizes traditional 'domestic' crafts like quilting and embroidery to elevate women's history and explore themes of labor, memory, and social connectivity.",
    workDescription: "Commissioned for the 19th Amendment Centennial, this quilt commemorates the suffrage movement while explicitly acknowledging the racial divide within it. It honors the women of color whose fight for voting rights continued long after 1920.",
    searchQuery: "Kassie Woodworth artist",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "17",
    name: "Shelby Nower",
    isAlive: true,
    title: "nINeteenth",
    medium: "Painting (Oil/Acrylic)",
    date: "2020",
    location: "Decatur / Indiana Statehouse",
    cause: "Women's Suffrage",
    bio: "Shelby Nower is a fine artist and muralist from Decatur, Indiana. She is known for her colorful, illustrative style and character-driven works that often bring historical figures or community narratives to life.",
    workDescription: "A celebratory painting depicting women triumphantly casting their first votes. Nower integrated the names of prominent Indiana suffragists into the clothing of the figures, turning the painting into a historical document of the movement's leaders.",
    searchQuery: "Shelby Nower artist",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "18",
    name: "Bonnie Fillenwarth",
    isAlive: true,
    title: "Her Flag (Indiana Stripe)",
    medium: "Mixed Media on Fabric",
    date: "2020",
    location: "Indianapolis (Work travels nationally)",
    cause: "Women's Suffrage",
    bio: "Bonnie Fillenwarth is an Indiana artist who works in painting and mixed media. She is deeply interested in women's history and uses her art to tell the stories of forgotten or underappreciated female figures.",
    workDescription: "Created as Indiana's contribution to the national 'Her Flag' collaborative project. The stripe illustrates key Hoosier suffragists, visually weaving Indiana's specific history into the larger national tapestry of the 19th Amendment ratification.",
    searchQuery: "Bonnie Fillenwarth artist",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "19",
    name: "Robert Indiana (Suffrage Work)",
    isAlive: false,
    born: "1928",
    died: "2018",
    title: "The Mother of Us All (Posters/Designs)",
    medium: "Lithography / Set Design",
    date: "1967 / 1976",
    location: "Various Collections",
    cause: "Women's Suffrage",
    bio: "Robert Indiana was a preeminent figure in the Pop Art movement. Beyond his famous 'LOVE' works, he was deeply engaged with American history and created visual tributes to key historical figures, including suffragists.",
    workDescription: "Indiana created the set design and costumes for the Virgil Thomson/Gertrude Stein opera 'The Mother of Us All', which chronicles the life of Susan B. Anthony. His pop-art aesthetic brought a modern, graphic energy to the story of the suffrage movement.",
    searchQuery: "Robert Indiana Mother of Us All",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "20",
    name: "Karen Boone",
    isAlive: true,
    title: "Natural Pigment Works",
    medium: "Painting / Mixed Media",
    date: "Ongoing",
    location: "Borden, Indiana",
    cause: "Environmental Justice",
    bio: "Karen Boone is a 'natural pigment painter' who forages for clay, ochre, and charcoal near her home in Southern Indiana. She processes these materials by hand to create zero-waste paints, making her entire artistic process an act of environmental stewardship.",
    workDescription: "Her abstract paintings are literal pieces of the Indiana landscape. By refusing commercial, toxic paints in favor of earth-based materials, her work advocates for a sustainable relationship with the land.",
    searchQuery: "Karen Boone artist Borden",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "21",
    name: "Justin Roberts & Shannon Davis-Roberts",
    isAlive: true,
    title: "Walk the Willow Sculptures",
    medium: "Willow Branches / Sculpture",
    date: "Ongoing",
    location: "Southern Indiana",
    cause: "Environmental Justice, Zero Waste",
    bio: "Justin and Shannon operate 'Walk the Willow,' a creative studio specializing in large-scale sculptures made from woven willow branches. They are committed to using sustainable, biodegradable materials that eventually return to the earth without harm.",
    workDescription: "Whimsical, large-scale woven sculptures (often figures or structures) that demonstrate how public art can be created with a zero-waste footprint. Their work emphasizes the beauty of natural, renewable materials.",
    searchQuery: "Walk the Willow",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "22",
    name: "Pat Rowbottom",
    isAlive: true,
    title: "Artists for Climate Awareness",
    medium: "Painting / Advocacy",
    date: "Ongoing",
    location: "Bloomington",
    cause: "Climate Change Awareness",
    bio: "Pat Rowbottom is a painter and a leader (Vice President) of the 'Artists for Climate Awareness' organization. She works to mobilize the arts community to address the climate crisis through exhibitions, education, and fundraising.",
    workDescription: "While her personal work often celebrates nature, her primary 'activist' work is organizational—facilitating exhibits that force the community to confront climate change and conservation issues.",
    searchQuery: "Pat Rowbottom artist Indiana",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "23",
    name: "Angelica Frausto (Nerdy Brown Kid)",
    isAlive: true,
    title: "Portraits/Illustrations",
    medium: "Digital Art / Graphic Design",
    date: "Ongoing",
    location: "South Bend",
    cause: "Immigration Detention Abolition",
    bio: "Angelica Frausto, known as 'Nerdy Brown Kid,' is a Xicana artist and social scientist. Her work is deeply rooted in the experiences of women of color and immigrants, often serving as visual advocacy for the abolition of immigration detention.",
    workDescription: "Her illustrations are often used in campaigns for organizations like the Detention Watch Network. They focus on the humanity, dreams, and resilience of those impacted by the immigration system, countering dehumanizing political narratives.",
    searchQuery: "Angelica Frausto Nerdy Brown Kid",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "24",
    name: "Beatriz Vasquez",
    isAlive: true,
    title: "Immigrantes Bienvenidos (Immigrants Welcome)",
    medium: "Papel Picado / Mural",
    date: "Ongoing",
    location: "Indianapolis",
    cause: "Immigration, Community Safety",
    bio: "Beatriz Vasquez is a Mexican-American 'artivist' who specializes in papel picado (cut paper). She transforms this delicate folk art tradition into large-scale, political statements about border culture, human rights, and the realities of the immigrant experience.",
    workDescription: "A public installation designed to signal safety and welcome to Latinx neighbors. It uses the imagery of the Monarch butterfly—a symbol of natural, borderless migration—to advocate for the free movement and dignity of people.",
    searchQuery: "Beatriz Vasquez artist Indianapolis",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "25",
    name: "Nasreen Khan",
    isAlive: true,
    title: "Paintings & Mixed Media",
    medium: "Visual Art / Scavenged Wood",
    date: "Ongoing",
    location: "Indianapolis (Haughville)",
    cause: "Immigration, Gender & LGBTQ+ Rights",
    bio: "Nasreen Khan is a queer, biracial, immigrant artist and writer. Living in the Haughville neighborhood, she uses art to explore 'the margins'—of race, gender, and geography—often using scavenged urban wood to highlight the resilience of nature in the city.",
    workDescription: "Her mixed media works often combine natural elements with personal narrative, grappling with the feeling of 'otherness' in the Midwest and challenging the viewer to see the beauty in the marginalized and the reclaimed.",
    searchQuery: "Nasreen Khan artist",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "26",
    name: "Jawshing Arthur Liou",
    isAlive: true,
    title: "Whispers from the Divide",
    medium: "Video Installation",
    date: "Recent",
    location: "Bloomington (IU Museum)",
    cause: "Immigration, Empathy",
    bio: "Jawshing Arthur Liou is a digital media artist and professor whose work often involves pilgrimages to sacred or politically charged sites. He uses high-definition video to create meditative, immersive experiences that deal with human tragedy and impermanence.",
    workDescription: "A video installation filmed along the US-Mexico border. Rather than focusing on political rhetoric, the work captures the atmospheric and physical reality of the borderlands, fostering empathy and offering a meditative look at the barriers we erect.",
    searchQuery: "Jawshing Arthur Liou Whispers from the Divide",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "27",
    name: "Thomas Hart Benton",
    isAlive: false,
    title: "A Social History of Indiana",
    medium: "Oil on Canvas Mural",
    date: "1933",
    location: "Bloomington (IU Auditorium)",
    cause: "Labor Rights",
    bio: "Thomas Hart Benton was a leader of the Regionalist art movement. His famous Indiana murals were radical for their time because they refused to whitewash history, depicting the KKK and honoring socialist labor leader Eugene V. Debs.",
    workDescription: "A sprawling mural cycle that places the laborer and the common person at the center of Indiana's history. It explicitly links the state's progress to the physical toil of its workers and acknowledges the political struggles of the working class.",
    searchQuery: "Thomas Hart Benton Indiana Murals",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "28",
    name: "John Fabion",
    isAlive: false,
    title: "Limestone Quarry Workers",
    medium: "Terra-Cotta Relief",
    date: "1942",
    location: "Bedford (U.S. Post Office)",
    cause: "Labor Rights",
    bio: "John Fabion was a WPA artist. His work in Bedford is a direct homage to the specific labor history of the 'Limestone Capital of the World'.",
    workDescription: "A relief sculpture capturing the dangerous and physically demanding work of quarrying limestone. It honors the dignity of the industrial worker during an era when labor rights were a central national conversation.",
    searchQuery: "John Fabion WPA artist",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "29",
    name: "William F. Kaeser",
    isAlive: false,
    title: "Loggers",
    medium: "Oil on Canvas Mural",
    date: "1941",
    location: "Pendleton (U.S. Post Office)",
    cause: "Labor Rights",
    bio: "William F. Kaeser was an Indiana artist who participated in the New Deal art programs. His work often focused on the honest depiction of rural and industrial labor.",
    workDescription: "A mural depicting the logging industry, emphasizing the collective effort and physical strength required by the workers, serving as a permanent tribute to the region's working-class roots.",
    searchQuery: "William F. Kaeser WPA",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "30",
    name: "Nat Werner",
    isAlive: false,
    title: "Rest during Prairie Plowing",
    medium: "Cast Stone Relief",
    date: "1940",
    location: "Fowler (U.S. Post Office)",
    cause: "Labor Rights",
    bio: "Nat Werner was a sculptor known for his socially conscious work. His WPA commission in Fowler reflects the agricultural backbone of the local economy.",
    workDescription: "A relief sculpture that humanizes the agricultural laborer, depicting a moment of rest. It acknowledges the exhaustion and humanity of the worker behind the agricultural production.",
    searchQuery: "Nat Werner WPA artist",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "31",
    name: "Artists At Work (Indianapolis Cohort)",
    isAlive: true,
    title: "Salaried Artist Employment Program",
    medium: "Program/Economic Model",
    date: "Ongoing (Since 2023)",
    location: "Indianapolis",
    cause: "Labor Rights for Artists",
    bio: "Modeled after the WPA, 'Artists At Work' is a workforce resilience program that puts artists on a salary with benefits. It treats art-making as essential labor, pairing artists with social impact organizations to serve the community.",
    workDescription: "This is not a single artwork but a radical labor model. It validates art as 'work' deserving of a living wage and health insurance, directly combating the precarious financial reality that many artists face.",
    searchQuery: "Artists At Work Indianapolis",
    imageUrl: "/placeholder.svg?height=400&width=600",
    link: "https://cicf.org/artists-at-work-indianapolis/"
  },
  {
    id: "32",
    name: "Robert Indiana (Robert Clark)",
    isAlive: false,
    born: "1928",
    died: "2018",
    title: "HOPE",
    medium: "Mixed Media / Sculpture",
    date: "2008",
    location: "Various Collections (Global)",
    cause: "Political Change",
    bio: "Robert Indiana was a preeminent figure in the Pop Art movement. His iconic 'LOVE' series is known worldwide, but he also engaged deeply with political themes, using his graphic style to support causes he believed in.",
    workDescription: "Created for Barack Obama's 2008 presidential campaign, the 'HOPE' sculpture utilizes Indiana's signature stacked typography. Proceeds from the print sales were donated to the campaign, marking a direct intersection of Pop Art and political activism.",
    searchQuery: "Robert Indiana HOPE sculpture",
    imageUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: "33",
    name: "Jeffrey A. Wolin",
    isAlive: true,
    title: "Written in Memory (Series)",
    medium: "Photography with Text",
    date: "1990s–2000s",
    location: "IU Bloomington",
    cause: "Social Justice, Holocaust Memory",
    bio: "Jeffrey A. Wolin is a photographer and professor known for his unique combination of portraiture and hand-written text. His work gives voice to his subjects, allowing them to write their own stories directly onto the photographic prints.",
    workDescription: "This series documents the stories of Holocaust survivors. By combining portraits with the survivors' own written memories, Wolin ensures these personal histories are preserved and witnesses to the atrocities of the past are honored.",
    searchQuery: "Jeffrey A. Wolin photographer",
    imageUrl: "/placeholder.svg?height=400&width=600"
  }
];